// Copyright 2021 @neatcoin/apps authors & contributors
// SPDX-License-Identifier: GPL-3.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/apps', version: '0.98.2-106' };
