name: Master
on:
  push:
    branches:
      - master

jobs:
  # publish to gh-pages
  www:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: yarn install --immutable | grep -v 'YN0013'
    - name: Build apps
      run: yarn build
    - name: Publish to Github Pages
      run: yarn publish-gh-pages