name: Master
on:
  push:
    branches:
      - master

jobs:
  # publish to gh-pages
  www:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    - name: Git setup
      run: |
        git config push.default simple
        git config merge.ours.driver true
        git config user.name "github-actions[bot]"
        git config user.email "action@github.com"
        git checkout master
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: yarn install --immutable | grep -v 'YN0013'
    - name: Build apps
      run: yarn build
    - name: Publish to Github Pages
      run: yarn polkadot-exec-ghpages --dist packages/apps/build --dest .
